google_analytics_id: UA-33449675-9

repository: https://github.com/iROCKBUNNY/Cookbook

timezone: Asia/Shanghai

title: Cookbook
description: My Home-made Recipes
keywords: Cookbook, Home-made, Recipes, iROCKBUNNY
url: https://cookbook.irockbunny.com

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net

contact: contact[at]irockbunny[dot]com
github: https://github.com/iROCKBUNNY

image: /images/logo.png
logo: /images/logo.png
icon: utensils

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- archive
- Gemfile
- Gemfile.lock
- script
- vendor